### ISSUE TITLE
Client > ./build.sh

### ISSUE THREAD

**Issue by keun-jang** [daerduoCarey/partnet_anno_system#21]
**Help needed to run this annotator**. Thanks in advance
>**Error**: Can't walk dependency graph: Cannot find module './config/backend.js' from '/home/zeb/Documents/jang/partnet_anno_system/client/part_hier_annotator.js'
    required by /home/zeb/Documents/jang/partnet_anno_system/client/part_hier_annotator.js
    at /home/zeb/.nvm/versions/node/v17.3.0/lib/node_modules/browserify/node_modules/resolve/lib/async.js:158:35
    at load (/home/zeb/.nvm/versions/node/v17.3.0/lib/node_modules/browserify/node_modules/resolve/lib/async.js:177:43)
    at onex (/home/zeb/.nvm/versions/node/v17.3.0/lib/node_modules/browserify/node_modules/resolve/lib/async.js:202:17)
    at /home/zeb/.nvm/versions/node/v17.3.0/lib/node_modules/browserify/node_modules/resolve/lib/async.js:15:69
    at FSReqCallback.oncomplete (node:fs:198:21)

**Comment by Mdemerdash** [comment]
you need to create backend.js from the available template
